import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.stories.@(js|jsx|ts|tsx)',
    './.storybook/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '1rem',
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1296px',
        '3xl': '1296px',
      },
    },

    extend: {
      fontSize: {
        xs: ['12px', '16px'],
        sm: ['14px', '18px'],
        md: ['16px', '24px'],
        base: ['100px', '120px'],
        lg: ['18px', '28px'],
        xl: ['20px', '24px'],
        '2xl': ['22px', '32px'],
        '3xl': ['24px', '32px'],
        '4xl': ['28px', '36px'],
        '5xl': ['40px', '48px'],
        '6xl': ['60px', '60px'],
        '7xl': ['65px', '78px'],
      },
      colors: {
        primary: 'var(--primary)',
        'orange-background': 'var(--orange-background)',
        'orange-foreground': 'var(--orange-foreground)',
        'blue-background': 'var(--blue-background)',
        'blue-foreground': 'var(--blue-foreground)',
        'dark-blue': 'var(--dark-blue)',
        'yellow-background': 'var(--yellow-background)',
        'light-yellow': 'var(--light-yellow)',
        'yellow-foreground': 'var(--yellow-foreground)',
        'gray-background': 'var(--gray-background)',
        'gray-foreground': 'var(--gray-foreground)',
        'light-gray': 'var(--light-gray)',
        'slate-blue': 'var(--slate-blue)',
        'sky-blue': 'var(--sky-blue)',
        'teal-blue': 'var(--teal-blue)',
        'forest-green': 'var(--forest-green)',
        'gradient-primary': 'var(--gradient-primary)',
        'inactive-background': 'var(--inactive-background)',

        'form-border-color': 'var(--form-border-color)',
        'form-shadow-color': 'var(--form-shadow-color)',
        'blue-border-color': 'var(--blue-border-color)',

        'destructive-background': 'var(--destructive-background)',
        'success-background': 'var(--success-background)',
        'info-background': 'var(--info-background)',
        'warning-background': 'var(--warning-background)',
      },
      fontFamily: {
        secondary: ['var(--font-secondary)'],
        primary: ['var(--font-primary)'],
      },
      spacing: {
        '6.5': '26px',
        '7.5': '30px',
        '13.5': '54px',
        '15': '60px',
        '17.5': '70px',
        '18': '72px',
        '21': '84px',
        '33.5': '134px',
        '29.25': '117px',
        '57': '228px',
        '70': '280px',
        '71': '284px',
        '76.5': '306px',
        '104': '416px',
        '105': '420px',
        '120': '480px',
        '126.75': '507px',
        '132': '528px',
        '145': '580px',
        '159': '636px',
        '177': '708px',
        '182.5': '730px',
      },
      boxShadow: {
        form: '0px 8px 32px 0px #11111a0d, 0px 4px 16px 0px #11111a0d',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '30px',
      },
    },
  },
} satisfies Config;
